using Gam.Core.Abstractions;

namespace Gam.Core.Models;

/// <summary>
/// A multi-query research plan generated by the LLM during the planning phase.
/// This is the core innovation of GAM's Deep Research - multiple queries per iteration.
/// </summary>
public record DeepResearchPlan
{
    /// <summary>High-level strategy description.</summary>
    public required string Strategy { get; init; }
    
    /// <summary>Sub-questions that need to be answered to fulfill the original request.</summary>
    public required IReadOnlyList<string> InfoNeeds { get; init; }
    
    /// <summary>Which retrieval tools to use: "keyword", "vector", "page_index".</summary>
    public required IReadOnlyList<string> Tools { get; init; }
    
    /// <summary>Multiple keyword queries for BM25 search.</summary>
    public required IReadOnlyList<string> KeywordQueries { get; init; }
    
    /// <summary>Multiple semantic queries for vector search.</summary>
    public required IReadOnlyList<string> VectorQueries { get; init; }
    
    /// <summary>Specific page indices to retrieve directly (from memory abstracts).</summary>
    public required IReadOnlyList<int> PageIndices { get; init; }
    
    /// <summary>Whether the research is complete (sufficient context gathered).</summary>
    public bool IsComplete { get; init; }
    
    /// <summary>Whether this is a temporal query (asking "when" something happened).</summary>
    public bool IsTemporalQuery { get; init; }
    
    /// <summary>Create an empty/default plan.</summary>
    public static DeepResearchPlan Empty => new()
    {
        Strategy = "No plan generated",
        InfoNeeds = Array.Empty<string>(),
        Tools = new[] { "keyword", "vector" },
        KeywordQueries = Array.Empty<string>(),
        VectorQueries = Array.Empty<string>(),
        PageIndices = Array.Empty<int>(),
        IsComplete = false,
        IsTemporalQuery = false
    };
}

/// <summary>
/// Result of LLM integration - synthesized context from search hits.
/// </summary>
public record IntegratedResult
{
    /// <summary>LLM-synthesized coherent context that addresses the query.</summary>
    public required string Content { get; init; }
    
    /// <summary>Page IDs that contributed to this result.</summary>
    public required IReadOnlyList<Guid> SourcePageIds { get; init; }
    
    /// <summary>Token count of the synthesized content.</summary>
    public int TokenCount { get; init; }
    
    /// <summary>Empty result singleton.</summary>
    public static IntegratedResult Empty => new()
    {
        Content = "",
        SourcePageIds = Array.Empty<Guid>(),
        TokenCount = 0
    };
}

/// <summary>
/// Result of the two-step reflection phase.
/// </summary>
public record ReflectionResult
{
    /// <summary>Is the current information sufficient to answer the query?</summary>
    public required bool IsSufficient { get; init; }
    
    /// <summary>If not sufficient, what specific follow-up queries would help?</summary>
    public IReadOnlyList<string>? FollowUpQueries { get; init; }
    
    /// <summary>Explanation of what information is missing (for debugging/logging).</summary>
    public string? GapAnalysis { get; init; }
    
    /// <summary>Create a "sufficient" result.</summary>
    public static ReflectionResult Sufficient => new()
    {
        IsSufficient = true,
        FollowUpQueries = null,
        GapAnalysis = null
    };
    
    /// <summary>Create a "needs more" result with follow-up queries.</summary>
    public static ReflectionResult NeedsMore(IReadOnlyList<string> followUps, string? gap = null) => new()
    {
        IsSufficient = false,
        FollowUpQueries = followUps,
        GapAnalysis = gap
    };
}

/// <summary>
/// Extended research step with Deep Research specific data.
/// </summary>
public record DeepResearchStep
{
    public required int Iteration { get; init; }
    public required ResearchPhase Phase { get; init; }
    public required string Summary { get; init; }
    public required TimeSpan Duration { get; init; }
    
    // Planning phase data
    public DeepResearchPlan? Plan { get; init; }
    
    // Search phase data  
    public int? QueriesExecuted { get; init; }
    public IReadOnlyList<RetrievalResult>? RetrievalResults { get; init; }
    
    // Integration phase data
    public IntegratedResult? IntegratedResult { get; init; }
    public int? PagesIntegrated { get; init; }
    
    // Reflection phase data
    public ReflectionResult? Reflection { get; init; }
    
    // Current context at end of phase
    public MemoryContext? CurrentContext { get; init; }
}

/// <summary>
/// Configuration for Deep Research behavior.
/// </summary>
public class DeepResearchOptions
{
    /// <summary>Maximum iterations of the Plan→Search→Integrate→Reflect loop.</summary>
    public int MaxIterations { get; set; } = 3;
    
    /// <summary>Maximum hits to process per iteration.</summary>
    public int MaxHitsPerIteration { get; set; } = 10;
    
    /// <summary>Maximum keyword queries per plan.</summary>
    public int MaxKeywordQueries { get; set; } = 5;
    
    /// <summary>Maximum vector queries per plan.</summary>
    public int MaxVectorQueries { get; set; } = 5;
    
    /// <summary>Top-K results per individual query.</summary>
    public int TopKPerQuery { get; set; } = 5;
    
    /// <summary>Maximum tokens in final context.</summary>
    public int MaxContextTokens { get; set; } = 8000;
    
    /// <summary>Minimum relevance score to include a result.</summary>
    public float MinRelevanceScore { get; set; } = 0.3f;
    
    // === ADR-0002 Phase 5: Relationship-aware retrieval ===
    
    /// <summary>Enable expansion of search results with related memories.</summary>
    public bool EnableRelationshipExpansion { get; set; } = true;
    
    /// <summary>Maximum related pages to add per source page during expansion.</summary>
    public int MaxRelatedPerSource { get; set; } = 2;
    
    /// <summary>Relationship types to use for expansion.</summary>
    public RelationshipType[] ExpansionRelationshipTypes { get; set; } = 
        [RelationshipType.RelatesTo, RelationshipType.Reinforces];
}
